### ISSUE TITLE
Spiny Lobster availability time

### ISSUE THREAD

**Issue by sdreyes** [cestislife/cestislife.github.io#1]
On the "Arriving with October" Northern Hemisphere graphic, the Spiny Lobster says "4am-9pm" when it should be "9pm-4am."
<img width="1081" alt="NH_oct_in" src="https://user-images.githubusercontent.com/42514855/94845821-36b71500-03ee-11eb-9a90-bd8946a7e9e4.png">

**Comment by cestislife** [comment]
Thank you, this has been fixed.
